services:
  app:
    container_name: webkarbon
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./api.webkarbon.bzh:/etc/letsencrypt/live/api.webkarbon.bzh:ro 
    depends_on:
      - app
    networks:
      - web

networks:
  web:
    driver: bridge
