server {
    listen 80;
    server_name api.webkarbon.bzh;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.webkarbon.bzh;

    ssl_certificate /etc/letsencrypt/live/api.webkarbon.bzh/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.webkarbon.bzh/privkey.pem;

    location / {
        proxy_pass http://webkarbon:3000;
    }
}
